

const LOCAL_STORAGE_ADDRESS = 'address'
const LAYOUT_MAX_WIDTH = '1200px'
const TELEGRAM_WEBAPP_PARAM = 'telegram_webapp'
const ADDRESS_PARAM = 'address'

export {  LOCAL_STORAGE_ADDRESS, LAYOUT_MAX_WIDTH, TELEGRAM_WEBAPP_PARAM, ADDRESS_PARAM };
